language: php

cache:
  directories:
    - $COMPOSER_CACHE_DIR

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=4.1.*

before_install:
  - composer self-update

install:
    - composer install --no-interaction --prefer-dist

script:
    - ./bin/phpunit --coverage-clover build/logs/clover.xml

addons:
  code_climate:
    repo_token: 69523150e5928797e06a99d9d5ae48ac4090ac40ff00fb13eafc4d3744e84ac6

after_success:
  - bin/test-reporter
